# docker-compose.yml
version: "3"
services:
  sniffles-genomics:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nrel-davis-worker-snifgeno:latest
    ports:
      - "8050:8050"
    environment:
      SERVER_PORT: 8050
      DEBUG_MODE: "True"
      PROCESS_INTERACTIVE_MODE: "False"
      PROCESS_ONLY_NEW_FILES: "True"
    volumes:
      - ../data/input:/data/input
      - ../data/workdir:/data/workdir
      - ../data/output:/data/output